summoner: provide phase 1 root during ceremony initialization
penumbra-zone/penumbra pull request #3183
Opened 2023-10-11 18:56 UTC by redshiftzero

Closes #3156

Note that I have intentionally not done the transition from the provided phase 1 to phase 2, which will be done in #3158 which I'll pick up after this one.

2023-10-11 19:41 UTC, cronokirby requested changes
My thinking was that instead initialization should be a separate command, rather than something done automatically.

The reason behind that is that then we could make this command take in a non-dummy root from an external source to populate things instead.

2023-10-12 19:02 UTC, redshiftzero commented
The commands we have now are:

```
Running `target/debug/summonerd --help`
summonerd v0.62.0-11-g6d156c5
Penumbra summoning ceremony coordinator

USAGE:
    summonerd [OPTIONS] <SUBCOMMAND>

OPTIONS:
    -h, --help                             Print help information
        --tokio-console <tokio-console>    Enable Tokio Console support [default: false]
    -V, --version                          Print version information

SUBCOMMANDS:
    generate-phase1    Generate a phase 1 root (for testing purposes)
    help               Print this message or the help of the given subcommand(s)
    init               Initialize the coordinator
    start              Start the coordinator
```

I tested this via:

1. Generate a test phase 1 root and store in a file (if we use an externally provided phase 1 root later we can delete this): 
```
cargo run --bin summonerd -- generate-phase1 --output testphase1.txt
```

2. Initialize the database using the provided phase 1 root:
```
cargo run --bin summonerd -- init --storage-dir /tmp/summonerd --phase1-root testphase1.txt
```

After this step the database exists and we can validate that the phase 1 root has been inserted in the database:

```
% sqlite3 /tmp/summonerd/ceremony.db
SQLite version 3.39.5 2022-10-14 20:58:05
Enter ".help" for usage hints.
sqlite> sqlite> select * from phase1_contributions;
0|1|������n���N9��H�\�7�Ȃ��A��,��T���%b��g
t��H�|
```

3. Now we start the summonerd server as before:

```
cargo run --bin summonerd -- start --storage-dir /tmp/summonerd --fvk YOURFVKHERE --node https://grpc.testnet-preview.penumbra.zone
```

2023-10-12 22:12 UTC, cronokirby commented on tools/summonerd/src/main.rs
> +                }
```suggestion
                reader.read_to_end(&mut phase_1_bytes)?;
```

I believe this should work

2023-10-12 22:14 UTC, cronokirby approved these changes
LGTM, I'll just apply my suggestion, check CI, and then merge

2023-10-12 22:14 UTC, cronokirby commented on tools/summonerd/src/main.rs
> +                }
(We're already doing buffered reads via BufReader)

2023-10-12 23:00 UTC, merged