refactor(cnidarium): split `commit` into `prepare_commit` and `commit_batch`
penumbra-zone/penumbra pull request #4122
Opened 2024-03-27 23:07 UTC by noot

refactor `commit` into `prepare_commit` and `commit_batch`. this allows a `StagedWriteBatch` to be prepared via `prepare_commit` and the actual writing the `StagedWriteBatch` to disk to occur in `commit_batch`. this allows us to get the root hash of the changes without requiring the data to be fully committed.

closes  #4095

2024-04-01 12:35 UTC, erwanor requested changes
Thanks for taking this on, this is great work and it unlocks a lot of cool things besides 0.38 support. There are a couple things we want to change before merging but overall ACK. I have put together a couple unit tests that I will add before merging, once we're done with review

2024-04-03 01:57 UTC, noot commented
@erwanor thanks for the review, comments addressed!

2024-04-03 14:54 UTC, erwanor approved these changes

2024-04-03 14:57 UTC, erwanor commented
Added some simple tests scenarios, will merge on green CI. This is really exciting! Thanks again for your work on this.

2024-04-03 15:14 UTC, merged