feat(staking): 🎽 `IdentityKey` is internally represented as bytes
penumbra-zone/penumbra pull request #4151
Opened 2024-04-02 19:49 UTC by cratelyn

work in progress.

fixes #2304.

2024-04-02 19:50 UTC, cratelyn commented
**NB:** while we should eventually move the `IdentityKey` type to `penumbra-keys`, that change is avoided for now. thus, `feat(staking)`.

2024-04-02 20:39 UTC, hdevalence commented
> **NB:** while we should eventually move the `IdentityKey` type to `penumbra-keys`, that change is avoided for now. thus, `feat(staking)`.

We shouldn't do this, the identity key is staking-specific, which is why it's in the staking component. Also, since the proto lives in the staking proto package, this isn't possible without deprecating the proto type and leaving a duplicate around. So we can plan to not do it.

2024-04-02 20:40 UTC, hdevalence commented on crates/core/component/stake/src/identity_key.rs
> +// decompressed: std::sync::OnceLock<VerificationKey<SpendAuth>>,
?

2024-04-02 20:41 UTC, hdevalence commented on crates/core/component/stake/src/identity_key.rs
> +}
This should just be a wrapper around the `VerificationKeyBytes`:
```rust
pub struct IdentityKey(pub VerificationKeyBytes<SpendAuth>)
```
All we want to be doing here is replacing `VerificationKey` with `VerificationKeyBytes`, nothing more or less.

2024-04-02 20:42 UTC, hdevalence commented on crates/core/component/stake/src/identity_key.rs
> +    }
We shouldn't be exposing this as part of the public API, it's not necessary for callers to have a convenient method for.

2024-04-02 20:44 UTC, hdevalence commented on crates/core/component/stake/src/identity_key.rs
> +}
I'm not sure it's desirable to have all of these impls. We didn't have them before, do we need them to change the internal representation?

2024-04-02 20:46 UTC, hdevalence requested changes
This PR adds a lot of code changes beyond the scope of the issue, which is changing `VerificationKey` to `VerificationKeyBytes`.

2024-04-03 00:16 UTC, erwanor commented
> We shouldn't do this, the identity key is staking-specific, which is why it's in the staking component. Also, since the proto lives in the staking proto package, this isn't possible without deprecating the proto type and leaving a duplicate around. So we can plan to not do it.

@hdevalence The `IdentityKey` proto definition already lives in `core.keys` so the current situation is a bit awkward fwiw

2024-04-03 00:17 UTC, hdevalence commented
Ah OK, in that case we should align it with the protos.

2024-04-03 21:28 UTC, cratelyn commented
this was an exploratory draft, and was not intended or ready to be reviewed. i'm going to close this in favor of #4152.

2024-04-03 21:28 UTC, closed without merging

2024-04-03 21:29 UTC, cratelyn commented
> **NB:** while we should eventually move the `IdentityKey` type to `penumbra-keys`, that change is avoided for now. thus, `feat(staking)`.

it seems we came to agreement on this point. i'll file an issue about it sometime this week.