ibc: delete packet commitments instead of writing empty values
penumbra-zone/penumbra pull request #4644
Opened 2024-06-19 18:38 UTC by avahowell

The IBC spec calls for deletion of packet commitments after a successful acknowledgement, in order to avoid double-acknowledgements.

Previously, our implementation accomplished this deletion by writing an empty byte slice vec![] to the commitment path.

However, this will cause nonexistence proofs by exclusion (the standard NX-proof type used in ics23) of adjacent keys to fail, since ics23 does not support existence proofs of empty values. We observed this when timeouts from osmosis testnet failed to verify the NX proofs from penumbra testnet.

This PR changes `delete_packet_commitment` to actually delete the commitment, and introduces a migration for testnet 78 that will delete all of the previously overwritten commitments.

2024-06-19 18:48 UTC, erwanor approved these changes
ACK on the change, and the migration looks correct too.

To test this, we can:

1. Halt a full node running the current chain
2. Perform the migration (using `--force`)
3. Start the node again with peering disabled
4. Run `pcli query key ibc-data/receipts/ports/transfer/channels/channel-8/sequences/28`
5. Observe `Not found`

2024-06-19 19:01 UTC, avahowell commented
One thing that occurred to me is that perhaps we should make a design change to the storage API to prevent writing empty keys, since any empty key (in the ibc substore) will cause this problem

2024-06-20 18:30 UTC, erwanor requested changes

2024-06-20 18:30 UTC, erwanor commented on crates/bin/pd/src/migrate/testnet78.rs
> +        delta.delete(key);
We'll have to re-apply the prefix here

2024-06-21 02:32 UTC, erwanor commented
```
Error: key not found! key=ibc-data/commitments/ports/transfer/channels/channel-7/sequences/7
```

We got it, while testing I found a couple issues with prefix caching, I will open issues shortly. This PR works though, so approving and merging on green CI.

2024-06-21 02:32 UTC, erwanor approved these changes
LGTM, tested the migration on current chain state.

2024-06-21 02:40 UTC, merged