ibc: fix logging of timestamp timeouts
penumbra-zone/penumbra pull request #4654
Opened 2024-06-24 19:35 UTC by avahowell

2024-06-24 19:36 UTC, cratelyn approved these changes

2024-06-24 19:36 UTC, zbuc requested changes

2024-06-24 19:36 UTC, zbuc commented on crates/core/component/ibc/src/component/packet.rs
>                  chain_ts,
can you change this to log `chain_ts.nanoseconds()` instead so the displayed types are the same?

2024-06-24 19:37 UTC, conorsch commented
During interchaintest integration work, @zbuc noticed that the logging message was structured. Loosely related to #4638 & #4636.

2024-06-24 19:38 UTC, zbuc approved these changes

2024-06-24 19:38 UTC, conorsch approved these changes

2024-06-24 19:39 UTC, avahowell commented
I just noticed that the timestamp used here is wrong, it should be using the consensus state timestamp. will fix

2024-06-25 00:56 UTC, merged

2024-06-25 15:24 UTC, conorsch commented
Marking this as consensus-breaking after the fact, because the diff makes substantive changes to how timeouts are handled. Please remove the label if inappropriate.