wip: update FMD parameters when needed in compact block
penumbra-zone/penumbra pull request #4715
Opened 2024-07-16 23:41 UTC by redshiftzero

## Describe your changes

This fixes the compact block generation such that updated FMD parameters are provided. This is required to use an algorithm in the future that dynamically updates the FMD parameters (see #1087)

## Issue ticket number and link

Closes #4714

## Checklist before requesting a review

- [ ] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > REPLACE THIS TEXT WITH RATIONALE (CAN BE BRIEF)

2024-07-17 06:23 UTC, cronokirby commented on crates/core/component/compact-block/src/component/manager.rs
> +        let fmd_parameters = if previous_fmd_params != current_fmd_params {
```suggestion
        let fmd_parameters = if previous_fmd_params != current_fmd_params && current_fmd_params.as_of_block_height == height {
```

2024-07-17 06:24 UTC, cronokirby commented on crates/core/component/compact-block/src/component/manager.rs
> +        let fmd_parameters = if previous_fmd_params != current_fmd_params {
e.g. if the params are:
```
0 0 0 0 0 0 1 1 1 1 1 1
```
we only want to send over the new params in the compact block where they changed

2024-07-17 17:53 UTC, cronokirby approved these changes

2024-07-17 19:18 UTC, conorsch commented
> This fixes the compact block generation

which means this is a consensus-breaking change, no? There's no rationale in the PR text explaining why it _isn't_ a consensus-breaking change, so I'm adding the tag. Please remove if I've misunderstood.

2024-07-17 20:15 UTC, cronokirby commented
It breaks consensus only for a dynamic FMD algorithm

2024-07-22 18:56 UTC, hdevalence commented
This would need to be added in a chain upgrade, then, and there are currently no plans for chain upgrades, pending emergence of a community-driven upgrade process. So we'd need to icebox it for now.

2024-07-24 19:00 UTC, conorsch requested changes
Requesting changes to block merge, pending chain-upgrade plans.

2024-08-05 20:15 UTC, closed without merging