feat: lp
penumbra-zone/penumbra pull request #4771
Opened 2024-07-25 20:17 UTC by vacekj

## Describe your changes

implements lp positions and execution indexing

## Issue ticket number and link

fixes #4739 

## Checklist before requesting a review

- [ ] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

indexer-only changes

2024-07-25 21:17 UTC, cronokirby commented
This is a good start, but I think we want to compute some more derived information for use in the explorer, for example the price, so that the explorer can easily sort and fetch by price.

2024-07-25 21:18 UTC, cronokirby requested changes
Let's clean up the accidental formatting changes and make sure that we have all the information we need to implement the APIs.

2024-07-25 21:18 UTC, conorsch commented
>This is a good start, but I think we want to compute some more derived information for use in the explorer

Downgrading to "draft", mostly to signal that we don't intend to block on upcoming point-release until this lands. Feel free to promote back to ready for review whenever, @vacekj!

2024-07-26 04:22 UTC, cronokirby commented
A few more things I noticed:
- We want to store the trading pair likely as a new derived type (tuple) of `(BYTEA, BYTEA)`
- We definitely need a table storing the current state of any given position, including permanent information like the trading pair, price, fees.
- We need to include the reserve amounts in the lp_updates table, to have a history of the reserves over time.

2024-07-29 14:55 UTC, vacekj commented
@cronokirby this leads me to believe we then have all we need in the data? Can we proceed to review and merge?

2024-07-29 16:55 UTC, cronokirby commented
I think we want:
- to store the price directly so that we can easily replicate the search by price queries
- to actually materialize each LP rather than computing it by taking the last seen update, because we need extra information like the price, and can avoid storing information that doesn't change in every update

but more broadly with this one we can actually test that it works by modifying the dex explorer raw indexing database queries to use it, and we should do that.

2024-07-29 17:38 UTC, cronokirby reviewed
It would also be nice if we didn't create a diff over the parts of the database we haven't changed, we can format in a separate PR

2024-07-30 06:05 UTC, cronokirby approved these changes
Looks good to me now, did some brief testing as well

2024-07-30 15:02 UTC, merged