fix penumbra-specific timestamp reads in ibc module
penumbra-zone/penumbra pull request #4822
Opened 2024-08-20 00:29 UTC by noot

## Describe your changes

fix penumbra-specific timestamp reads in ibc module by using `HostInterface` instead. 

- `Ics20WithdrawalWithHandler` was created analogously to `IbcRelayWithHandler`, which attaches a `HostInterface` to be used in `check_and_execute` to get the current block timestamp
- the rpc method `client_state` was also updated to use `HostInterface`

## Issue ticket number and link

#4812

## Checklist before requesting a review

- [ ] If this code contains consensus-breaking changes, I have added the "consensus-breaking" label. Otherwise, I declare my belief that there are not consensus-breaking changes, for the following reason:

  > the timestamp reads are unchanged for penumbra, as the `PenumbraHost` is used, which calls the same methods as before

2024-08-20 18:52 UTC, zbuc approved these changes

2024-08-21 16:58 UTC, conorsch requested changes
The penumbra-ibc changes break wasm compatibility, which would break web code.

2024-08-21 17:21 UTC, turbocrime commented
wasm crate seems to build fine with this alternate patch. what's the difference here?

```patch
diff --git a/packages/wasm/crate/Cargo.toml b/packages/wasm/crate/Cargo.toml
index c78cd16f7..a58548b8e 100644
--- a/packages/wasm/crate/Cargo.toml
+++ b/packages/wasm/crate/Cargo.toml
@@ -14,21 +14,21 @@ default = ["console_error_panic_hook"]
 mock-database = []
 
 [dependencies]
-penumbra-auction = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-auction", default-features = false }
-penumbra-asset = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-asset" }
-penumbra-compact-block = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-compact-block", default-features = false }
-penumbra-dex = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-dex", default-features = false }
-penumbra-fee = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-fee", default-features = false }
-penumbra-governance = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-governance", default-features = false }
-penumbra-keys = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-keys" }
-penumbra-num = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-num" }
-penumbra-proof-params = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-proof-params", default-features = false }
-penumbra-proto = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-proto", default-features = false }
-penumbra-sct = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-sct", default-features = false }
-penumbra-shielded-pool = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-shielded-pool", default-features = false }
-penumbra-stake = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-stake", default-features = false }
-penumbra-tct = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-tct" }
-penumbra-transaction = { git = "https://github.com/penumbra-zone/penumbra.git", tag = "v0.80.0", package = "penumbra-transaction", default-features = false }
+penumbra-auction = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-auction", default-features = false }
+penumbra-asset = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-asset" }
+penumbra-compact-block = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-compact-block", default-features = false }
+penumbra-dex = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-dex", default-features = false }
+penumbra-fee = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-fee", default-features = false }
+penumbra-governance = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-governance", default-features = false }
+penumbra-keys = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-keys" }
+penumbra-num = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-num" }
+penumbra-proof-params = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-proof-params", default-features = false }
+penumbra-proto = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-proto", default-features = false }
+penumbra-sct = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-sct", default-features = false }
+penumbra-shielded-pool = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-shielded-pool", default-features = false }
+penumbra-stake = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-stake", default-features = false }
+penumbra-tct = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-tct" }
+penumbra-transaction = { git = "https://github.com/penumbra-zone/penumbra.git", branch = "noot/host-interface-fix", package = "penumbra-transaction", default-features = false }
 
 anyhow = "1.0.86"
 ark-ff = { version = "0.4.2", features = ["std"] }
```

2024-08-21 17:26 UTC, turbocrime commented
notably wasm doesn't depend on the ibc crate at all, lol. maybe that is the difference

2024-08-21 18:16 UTC, turbocrime commented on crates/core/component/ibc/Cargo.toml
is there any problem with restoring the previous Cargo.toml configuration? it seems to build fine, and satisfies the compat checker

2024-08-21 18:18 UTC, turbocrime commented on crates/core/component/ibc/Cargo.toml
is there any problem with restoring the previous Cargo.toml configuration? it seems to build fine, and satisfies the compat checker

2024-08-21 18:33 UTC, turbocrime approved these changes
built and manually tested prax with this branch, both before and after my commit. testnet ibc roundtrips successful. afaict it's fully functional so it's fine by me

2024-08-21 18:37 UTC, conorsch commented
Excellent, thanks for the assist, @turbocrime! I'm not sure why my toml patch gave inaccurate results, but I agree with your solution, and appreciate the manual testing via local builds. My concerns are address, I'm happy to merge.

2024-08-21 18:37 UTC, conorsch approved these changes

2024-08-21 18:38 UTC, merged

2024-08-21 18:39 UTC, conorsch commented
@noot for now, please use a git dep against the latest commit on main: `87adc8d6b15f6081c1adf169daed4ca8873bd9f6`. We'll likely have a v0.80.3 tag up in a week or two.